name: EUP/Kleding
description: EUP/kleding gerelateerde issues
title: "[EUP]: "
labels: ["bug", "EUP - interiors - retextures", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Bedankt dat je de tijd wilt nemen om een issue aan te maken!
        Vul de onderstaande dingen aub zo gedetailleerd mogelijk in zodat we de issue snel kunnen afhandelen.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Hoe kunnen we je contacteren op Discord als we extra informatie nodig zijn?
      placeholder: "Voorbeeld: Misstake#1337"
    validations:
      required: false
  - type: dropdown
    id: where
    attributes:
      label: Waar bevind de issue zich?
      options:
        - EUP/Kleding
        - Interiors
        - Andere textures
    validations:
      required: true
  - type: textarea
    id: what-wrong
    attributes:
      label: Wat klopt er niet
      description: Wat klopt er niet aan de textures, eventueel screenshots van wat er niet klopt.
      placeholder: "Voorbeeld: Van een afstand is de texture geel."
  - type: markdown
    attributes:
      value: |
        Door deze issue aan te maken ga je akkoord met onze [contributing](https://github.com/Tedeapolis/development/blob/master/CONTIBUTING.md) richtlijnen
