name: Feature request
description: Vraag een nieuwe feature aan
title: "[FEATURE]: "
labels: ["enhancement", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Bedankt dat je de tijd wilt nemen om een issue aan te maken!
        Vul de onderstaande dingen aub zo gedetailleerd mogelijk in zodat we de issue snel kunnen afhandelen.
        
        **Wanneer je langere teksten maakt vergeet dan niet gebruik te maken van OPMAAK! (headings/kopjes per onderwerp etc)**
        Dit zorgt ervoor dat het overzichtelijk blijft en we je issue waarschijnlijk sneller op zullen pakken
        
        Voor opmaak hulp zie [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (Dit is sws handig om te weten want werkt ook volledig in Discord berichten)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Hoe kunnen we je contacteren op Discord als we extra informatie nodig zijn?
      placeholder: "Voorbeeld: Misstake#1337"
    validations:
      required: false
  - type: input
    id: goedkeuring
    attributes:
      label: Goedgekeurd door
      description: Is deze issue door iemand goedgekeurd? Zo ja, vul dan hier de persoon z'n Discord tag in.
      value: "N.V.T."
  - type: textarea
    id: feature-description
    attributes:
      label: "Beschrijf zo duidelijk mogelijk de feature"
    validations:
      required: true
  - type: textarea
    id: solves
    attributes:
      label: "Wat lost deze feature op?"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Richtlijnen
      description: Door deze issue aan te maken ga je akkoord met onze [contributing](https://github.com/Tedeapolis/development/blob/master/CONTRIBUTING.md) richtlijnen
      options:
        - label: Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen
          required: true
